### ISSUE TITLE
Map: change ecosystem group layer opacity

### ISSUE THREAD

**Issue by tmfrnz** [red-list-ecosystem/typology-map#21]
As a public user, I want to be able 

* to adjust the current ecosystem group layer opacity

so I can balance visibility of group layer and underlying basemap (#3)

**Comment by jrfep** [comment]
Hi @tmfrnz 
It looks like this only works when the map is expanded, right?
I think some user would miss that at first glance, would it be possible to add a hint somewhere (like: "expand map for further options"...).

**Comment by tmfrnz** [comment]
Agreed, @jrfep! Happy to consider offering the settings already on the small view (maybe available through a "settings" button) or alternatively add a hint
