### ISSUE TITLE
Search: find realms, biomes, or groups 

### ISSUE THREAD

**Issue by tmfrnz** [red-list-ecosystem/typology-map#22]
As a public user, I want to

* search a realm, biome or ecosystem group by name or identifier

so I can quickly find the information I am interested in

**Comment by jrfep** [comment]
I think we need to add a list of synonyms for some groups. Users will likely search for "Mangrove" instead of "Intertidal forests and shrublands" or "Paramos" / "Andes" instead of "Tropical alpine", etc.

**Comment by tmfrnz** [comment]
While we could potentially even consider a full text search in the future, a list of relevant keywords for each typology item would be a bit easier to implement.

I could think of 2 options for a keyword search:

1. Add keywords as comma-separated list to the [config files](https://github.com/red-list-ecosystem/typology-map-data/tree/master/data/config), just as we do for the title. The benefit would be that this is very easy to implement as we already have everything in place
2. Add keywords as meta data ("front matter") to our markdown [content files](https://github.com/red-list-ecosystem/typology-map-content/tree/master/_posts), generate a static index (will be done automatically anytime a content element is updated) that we then download to enhance the search. This is slightly more effort but the benefit would be that the relevant keywords are maintained together with the content they represent.

**Comment by tmfrnz** [comment]
Will go with option 1 for now

- [x] add keyword list to config file and include in search

Also

- [x] enable search on small screens

**Comment by tmfrnz** [comment]
@jrfep you can now enter keywords as comma-separated lists in the typology [config files](https://github.com/red-list-ecosystem/typology-map-data/tree/master/data/config). You will find an example field that you can use as a template for each first typology item
