### ISSUE TITLE
Red List of Ecosystems logo

### ISSUE THREAD

**Issue by jrfep** [red-list-ecosystem/typology-map#33]
Need to add the new IUCN Red List of Ecosystem logo (official launch in September but we can start using it):

* Full version in the logo bar (welcome page)
* Small version (maybe monochrome white version?) on top left corner, always visible
* Should we also add the logos to the about page?

@sylvhay should have a copy of the logo specifications.

**Comment by tmfrnz** [comment]
> Need to add the new IUCN Red List of Ecosystem logo (official launch in September but we can start using it):
> 
> * Full version in the logo bar (welcome page)
> * Small version (maybe monochrome white version?) on top left corner, always visible
> * Should we also add the logos to the about page?
> 
> @sylvhay should have a copy of the logo specifications.

That all sounds good. @sylvhay if you could share with us any image files (ideally also including svg/vector version) and specs (eg to check if white version in header would be permissable and minimum size etc)

Happy to add the footer with logos to the about page (and could also consider other pages)

**Comment by sylvhay** [comment]
@tmfrnz @dmprk you should be able to access logos here: https://drive.google.com/drive/folders/1XNI7oEM342mzJ5c7gynkfibHMzU65YNe
there is a pdf in there with specs for use : 
https://drive.google.com/file/d/1lH1j-nEnsGCGsfnqu25Dg9hJxLPPbfSj/view?usp=sharing

**Comment by tmfrnz** [comment]
@sylvhay we are wondering if you would like us to change (some of) the site headings to use the logo font (Kanit bold)? 
(this would be an easy update)

**Comment by sylvhay** [comment]
@tmfrnz if you think it looks good, that sounds like a good idea.

**Comment by tmfrnz** [comment]
thanks for confirming, will pack this into the next update
