### ISSUE TITLE
Text overlapping in Explore sidebar

### ISSUE THREAD

**Issue by sylvhay** [red-list-ecosystem/typology-map#34]
I am getting overlapping text of the Realm and Biome labels in the sidebar, have only seen this within the Freshwater and Marine realms however?

![Fullscreen capture 21072020 14146 PM bmp](https://user-images.githubusercontent.com/58276776/88010735-f1a67500-cb58-11ea-986e-76883f2ca3e4.jpg)

**Comment by tmfrnz** [comment]
will be resolved in next update
