### ISSUE TITLE
Add emphasis for EFG summaries

### ISSUE THREAD

**Issue by sylvhay** [red-list-ecosystem/typology-map#35]
Is it possible to add some kind of emphasis for the Ecosystem Group Summaries? To make them stand out from the rest of the text, particularly because there is some repetition between these and the main text for each group. 

We were originally thinking a box of some kind - only if it doesnt interfere with the overall design or add clutter. I cant remember if this was ever discussed?

**Comment by tmfrnz** [comment]
related to #8

**Comment by tmfrnz** [comment]
@sylvhay yes, we agree the first paragraph should be emphasised but have instead suggested a slightly larger lead-style design
![image](https://user-images.githubusercontent.com/5811956/88040426-29a5bc00-cb49-11ea-8403-cacef9d482cf.png)

**Comment by tmfrnz** [comment]
This will automatically target the first paragraph, but in case the summary requires multiple paragraphs, I would suggest to make use of markdown's blockquote formatting `> paragraph` as well as using HTML tags `<p class="lead">paragraph</p>`

So in case multiple paragraphs are needed, the code should look like: 

With blockquote `> `

```
> first paragraph first paragraph first paragraph first paragraph first paragraph first paragraph first paragraph first paragraph first paragraph first paragraph
>
> second paragraph second paragraph second paragraph second paragraph second paragraph second paragraph second paragraph second paragraph second paragraph second paragraph second paragraph 
```

With HTML `<p class="lead">...</p>`

```
<p class="lead">first paragraph first paragraph first paragraph first paragraph first paragraph first paragraph first paragraph first paragraph first paragraph first paragraph</p>
<p class="lead">second paragraph second paragraph second paragraph second paragraph second paragraph second paragraph second paragraph second paragraph second paragraph second paragraph second paragraph</p> 
```

The advantage of using the former is that is easier to use and thus less error prone. However it would also mean that we could not use the blockquote syntax for actual quotes (at least not on the group pages).

**Comment by tmfrnz** [comment]
all 3 options have been implemented and will be supported from the next update

**Comment by tmfrnz** [comment]
note that `<p class="lead">` should also work on any other content markdown page
